<?php

function idm_views_query_alter(&$view, &$query) {
  if ($view->name == 'orglist' || $view->name =='mode_directory') {
    if ($view->name == 'orglist') {
      $query->where[2]['conditions'][0]['field'] = 'civicrm_contact.organization_name';
    }
    unset($query->table_queue['civicrm_contact_civicrm_website'], $query->table_queue['civicrm_contact_civicrm_website_1']);
    unset($query->relationships['civicrm_contact_civicrm_website'], $query->relationships['civicrm_contact_civicrm_website_1']);
    unset($query->tables['civicrm_contact_civicrm_website'], $query->tables['civicrm_contact_civicrm_website_1']);
    unset($query->tables['civicrm_contact']['civicrm_contact_civicrm_website'], $query->tables['civicrm_contact']['civicrm_contact_civicrm_website_1']);
    
    $query->table_queue['civicrm_contact_civicrm_website__civicrm_website']['join']->left_table = 'civicrm_contact';
    $query->table_queue['civicrm_contact_civicrm_website_1__civicrm_website']['join']->left_table = 'civicrm_contact';
    
    // main website type
    $query->table_queue['civicrm_website']['join']->extra[] = array(
      'value' => 6,
      'numeric' => 1,
      'field' => 'website_type_id',
      'operator' => '=',
    );
    // twitter website type
    $query->table_queue['civicrm_contact_civicrm_website_1__civicrm_website']['join']->extra[] = array(
      'value' => 4,
      'numeric' => 1,
      'field' => 'website_type_id',
      'operator' => '=',
    );
    // facebook website type
    $query->table_queue['civicrm_contact_civicrm_website__civicrm_website']['join']->extra[] = array(
      'value' => 3,
      'numeric' => 1,
      'field' => 'website_type_id',
      'operator' => '=',
    );
  }
}
